apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'django-app'
        static_configs:
          - targets: ['<django-service-name>:8000']

      - job_name: 'mysql'
        static_configs:
          - targets: ['<mysql-service-name>:9104']

    remote_write:
      - url: "https://<grafana-cloud-remote-write-url>"
        basic_auth:
          username: "<grafana-cloud-username>"
          password: "<grafana-cloud-api-key>"
